### ISSUE TITLE
Java 17 Compatibility

### ISSUE THREAD

**Issue by a1730** [forax/exotic#3]
Hi @forax,

Thank you for this little gem of a library. It strikes nice balance for our use.

You might be interested that exotic uses [defineAnonymousClass](https://github.com/forax/exotic/blob/ae4be6aa8e668a473d7771099fe1fa2ed56c0cc1/src/main/java/com.github.forax.exotic/com/github/forax/exotic/ObjectSupports.java#L34) which was removed in Java 17.
This is not a deal breaker for us - just FYI.

Thank you again.

**Comment by forax** [comment]
yes, i should take a look.

**Comment by forax** [comment]
Hi, the latest version seems to run with Java 17 & 18 (technically Java 15+).
A nice side effect is that the code does not use Unsafe anymore.

Let me now if i can close the issue.

**Comment by forax** [comment]
I've tagged a version 1.4.0

**Comment by a1730** [comment]
Awesome! Javadocs too!!
Thank you very much Prof @forax:)
